import type { InlineConfig } from "vite";
import { build as viteBuild } from "vite";
import fs from "fs";
import path from "path";
import { BuildError } from "../errors";
import { logger } from "../logger";
import type { ServerBuildOptions, BuildContext } from "../types";
import {
  packageJsonGenerator,
  typeGenerator,
  rewriteRuntimeTypeImports,
  cjsWrapper,
  esmWrapper,
} from "./plugins";

async function build(
  serverOpts: ServerBuildOptions,
  buildContext: BuildContext,
): Promise<void> {
  const {
    srcDir = "./server",
    entry = "index.ts",
    format = "esm",
    external = [],
    bundled = [],
    types = true,
    nodeTarget = "node22",
  } = serverOpts;

  const entries = Array.isArray(entry) ? entry : [entry];
  const resolvedSrcDir = path.resolve(srcDir);
  const entryPoints = {};
  for (const entry of entries) {
    const entryFilePath = path.join(resolvedSrcDir, entry);
    if (fs.existsSync(entryFilePath)) {
      const fileName = entry.replace(/\.ts$/, "");
      entryPoints[fileName] = entryFilePath;
    }
  }
  if (Object.keys(entryPoints).length === 0) {
    logger.warn("No server entry points found");
    return;
  }

  const isEsm = format === "esm";

  const plugins = [
    packageJsonGenerator({
      outDir: buildContext.outDir,
      bundled,
      types: types && !buildContext.isDev,
      entryNames: Object.keys(entryPoints),
      format,
    }),
    isEsm ? esmWrapper() : cjsWrapper(),
  ];

  if (types && !buildContext.isDev) {
    plugins.push(
      ...typeGenerator({
        srcDir: resolvedSrcDir,
        outDir: buildContext.outDir,
        entryFiles: Object.values(entryPoints),
      }),
    );
  }

  const config: InlineConfig = {
    configFile: false,
    logLevel: "warn",
    plugins,
    build: {
      outDir: buildContext.outDir,
      emptyOutDir: false,
      sourcemap: buildContext.isDev ? "inline" : true,
      minify: !buildContext.isDev,
      lib: {
        entry: entryPoints,
        formats: [isEsm ? "es" : "cjs"],
      },
      rollupOptions: {
        external,
        output: {
          entryFileNames: isEsm ? "[name].mjs" : "[name].js",
          exports: isEsm ? undefined : "auto",
          preserveModules: false,
        },
      },
    },
    esbuild: {
      platform: "node",
      target: nodeTarget,
      keepNames: true,
      tsconfigRaw: "{}",
    },
  };

  try {
    await viteBuild(config);

    // The emitted .d.ts imports from `@bonsae/nrg/server` (required so types
    // resolve during generation). The published node depends on the runtime,
    // so rewrite the declaration imports to match.
    if (types && !buildContext.isDev) {
      rewriteRuntimeTypeImports(buildContext.outDir, Object.keys(entryPoints));
    }

    // Generate CJS bridge so Node-RED can require() the ESM bundle
    if (isEsm) {
      const bridgeCode = `\
'use strict';
// CJS bridge — auto-generated by @bonsae/nrg/vite
// Node-RED uses require() to load packages. This bridge delegates to the ESM bundle.
module.exports = function (RED) {
    (async () => {
        const mod = await import("./index.mjs");
        if (typeof mod.default !== 'function') {
            throw new Error('ESM bundle must export a default function(RED)');
        }
        await mod.default(RED);
    })().catch(function (err) {
        RED.log.error('Failed to load ESM bundle: ' + err.message);
    });
};
`;
      fs.writeFileSync(path.join(buildContext.outDir, "index.js"), bridgeCode);
    }
  } catch (error) {
    throw new BuildError("server", error as Error);
  }
}

export { build };
