import type { TObject } from "@sinclair/typebox";
import type { RED } from "../../server/types";
import { Node } from "./node";
import type { IONodeContext, IONodeStatus, IONodeConfig, IONodeCredentials } from "./types";
declare abstract class IONode<TConfig = any, TCredentials = any, TInput = any, TOutput = any, TSettings = any> extends Node<TConfig, TCredentials, TSettings> {
    static readonly align?: "left" | "right";
    static readonly color: `#${string}`;
    static readonly labelStyle?: "node_label" | "node_label_italic" | string;
    static readonly icon?: string;
    static readonly paletteLabel?: string;
    static readonly inputs?: number;
    static readonly outputs?: number;
    static readonly inputLabels?: string | string[];
    static readonly outputLabels?: string | string[];
    static readonly inputSchema?: TObject;
    static readonly outputsSchema?: TObject;
    static readonly validateInput: boolean;
    static readonly validateOutput: boolean;
    private _send;
    readonly config: IONodeConfig<TConfig>;
    protected readonly context: IONodeContext;
    constructor(RED: RED, node: any, config: IONodeConfig<TConfig>, credentials: IONodeCredentials<TCredentials>);
    abstract input(msg: TInput): void | Promise<void>;
    send(msg: TOutput): void;
    status(status: IONodeStatus): void;
    updateWires(wires: string[][]): void;
    receive(msg: TInput): void;
    get x(): number;
    get y(): number;
    get g(): string | undefined;
    get wires(): string[][];
    get credentials(): IONodeCredentials<TCredentials> | undefined;
}
export { IONode };
