import type { Plugin } from "vite";
import path from "path";
import fs from "fs";
import mime from "mime-types";
import { nodeDefsPath } from "../../utils";

const VIRTUAL_ID = "virtual:nrg/node-definitions";
const RESOLVED_ID = "\0" + VIRTUAL_ID;

function resolveIcon(iconsDir: string, type: string): string | undefined {
  if (!fs.existsSync(iconsDir)) return undefined;
  return fs.readdirSync(iconsDir).find((f) => {
    if (path.basename(f, path.extname(f)) !== type) return false;
    const mimeType = mime.lookup(f);
    return mimeType !== false && mimeType.startsWith("image/");
  });
}

function nodeDefinitionsInliner(
  serverOutDir: string,
  entryPath: string,
  iconsDir?: string,
  componentsDir?: string,
  nodesDir?: string,
  hasUserEntry: boolean = true,
  // Cache directory for generated files (inside node_modules, gitignored).
  // Provided by the caller so it stays consistent with the generated entry path
  // and is isolated per output dir. Defaults to the shared location for any
  // standalone use.
  cacheDir: string = path.resolve("node_modules", ".nrg", "client"),
): Plugin {
  let _nodeTypes: string[] = [];
  let _definitions: Record<string, any> = {};

  return {
    name: "vite-plugin-node-red:client:node-definitions-inliner",
    enforce: "pre",

    // Read the node definitions the server build extracted (from executing the
    // just-built bundle) and add the icon — the only field resolved client-side,
    // from the resources dir. Populated before any load/transform hook runs.
    buildStart() {
      _nodeTypes = [];
      _definitions = {};

      const defsFile = nodeDefsPath(serverOutDir);
      const { nodeTypes, definitions } = fs.existsSync(defsFile)
        ? (JSON.parse(fs.readFileSync(defsFile, "utf-8")) as {
            nodeTypes: string[];
            definitions: Record<string, any>;
          })
        : { nodeTypes: [], definitions: {} };

      _nodeTypes = nodeTypes;
      for (const type of _nodeTypes) {
        _definitions[type] = {
          ...definitions[type],
          icon: iconsDir ? resolveIcon(iconsDir, type) : undefined,
        };
      }

      // When no user entry, generate node definition files in cache
      // so they appear as separate files in browser devtools.
      if (!hasUserEntry) {
        const nodesCache = path.resolve(cacheDir, "nodes");
        if (fs.existsSync(nodesCache)) {
          fs.rmSync(nodesCache, { recursive: true });
        }
        fs.mkdirSync(nodesCache, { recursive: true });

        for (const type of _nodeTypes) {
          // Skip if user has a physical node definition file
          const userTsPath = nodesDir
            ? path.resolve(nodesDir, `${type}.ts`)
            : null;
          if (userTsPath && fs.existsSync(userTsPath)) continue;

          const content = [
            `// auto-generated by nrg`,
            `import { defineNode } from "@bonsae/nrg/client";`,
            ``,
            `export default defineNode({`,
            `  type: ${JSON.stringify(type)},`,
            `});`,
            ``,
          ].join("\n");
          fs.writeFileSync(path.resolve(nodesCache, `${type}.ts`), content);
        }

        // Also write the entry file to cache
        const entryContent = generateEntryCode("");
        fs.mkdirSync(path.dirname(path.resolve(cacheDir, "index.ts")), {
          recursive: true,
        });
        fs.writeFileSync(path.resolve(cacheDir, "index.ts"), entryContent);
      }
    },

    resolveId(id) {
      if (id === VIRTUAL_ID) return RESOLVED_ID;
    },

    load(id) {
      if (id === RESOLVED_ID)
        return `export default ${JSON.stringify(_definitions)};`;

      // For auto-generated entries, return the generated code directly
      // so the browser devtools shows the actual source instead of the
      // placeholder comment on disk.
      if (!hasUserEntry && id === entryPath) {
        return generateEntryCode("");
      }
    },

    transform(code, id) {
      if (id !== entryPath) return;
      // When the user provides their own entry, prepend the generated
      // code to their source. For auto-generated entries, the load hook
      // already returned the full code.
      if (!hasUserEntry) return;

      return { code: generateEntryCode(code), map: null };
    },
  };

  function generateEntryCode(userCode: string): string {
    const nrgImports = new Set<string>(["__setSchemas"]);
    const lines = [`import __nrgSchemas from "${VIRTUAL_ID}";`];
    const postLines: string[] = [`__setSchemas(__nrgSchemas);`];

    // Auto-detect form components by convention: {componentsDir}/{type}.vue
    if (componentsDir && fs.existsSync(componentsDir)) {
      const formImports: string[] = [];
      const formEntries: string[] = [];

      for (const type of _nodeTypes) {
        const componentPath = path.resolve(componentsDir, `${type}.vue`);
        if (fs.existsSync(componentPath)) {
          const varName = `__nrgForm_${type.replace(/-/g, "_")}`;
          formImports.push(
            `import ${varName} from ${JSON.stringify(componentPath)};`,
          );
          formEntries.push(`${JSON.stringify(type)}: ${varName}`);
        }
      }

      if (formImports.length > 0) {
        lines.push(...formImports);
        nrgImports.add("__setForms");
        postLines.push(`__setForms({ ${formEntries.join(", ")} });`);
      }
    }

    // Auto-register only when no user entry was provided.
    if (!hasUserEntry) {
      const nodesCache = path.resolve(cacheDir, "nodes");
      const defVarNames: string[] = [];

      for (const type of _nodeTypes) {
        const varName = `__nrgNodeDef_${type.replace(/-/g, "_")}`;
        // Use physical file if user has one, otherwise use cached generated file
        const userTsPath = nodesDir
          ? path.resolve(nodesDir, `${type}.ts`)
          : null;
        const tsPath =
          userTsPath && fs.existsSync(userTsPath)
            ? userTsPath
            : path.resolve(nodesCache, `${type}.ts`);
        lines.push(`import ${varName} from ${JSON.stringify(tsPath)};`);
        defVarNames.push(varName);
      }

      if (defVarNames.length > 0) {
        nrgImports.add("registerTypes");
        postLines.push(`registerTypes([${defVarNames.join(", ")}]);`);
      }
    }

    // Build the @bonsae/nrg/client import line
    const importLine = `import { ${[...nrgImports].join(", ")} } from "@bonsae/nrg/client";`;
    lines.splice(1, 0, importLine);

    lines.push(...postLines);
    lines.push("");
    return lines.join("\n") + userCode;
  }
}

export { nodeDefinitionsInliner };
